// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type User struct {
	ID            int32
	Name          string
	Email         string
	Password      sql.NullString
	OauthProvider sql.NullString
	OauthID       sql.NullString
	Verified      bool
	Created       sql.NullTime
	Updated       sql.NullTime
}
